
Global:
  use_gpu: true
  epoch_num: 30  # Можем уменьшить из-за большего датасета
  log_smooth_window: 20
  print_batch_step: 50  # Увеличиваем из-за большего количества батчей
  save_model_dir: /kaggle/working/country_code_rec_model_augmented
  save_epoch_step: 5
  eval_batch_step: [0, 1000]
  cal_metric_during_train: true
  pretrained_model: null
  character_dict_path: /kaggle/working/dict_country_codes.txt
  character_type: en
  max_text_length: 3
  infer_mode: false
  use_space_char: false

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005  # Уменьшаем LR для стабильности
  regularizer:
    name: L2
    factor: 0.00001

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/working/
    label_file_list: ['/kaggle/working/train_list_augmented.txt']
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: true
    batch_size_per_card: 64  # Увеличиваем batch size
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/working/
    label_file_list: ['/kaggle/working/test_list_original.txt']
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: false
    batch_size_per_card: 64
    drop_last: false
    num_workers: 4
